# Generated by Django 6.0.3 on 2026-03-16 10:03

import django.db.models.deletion
import wagtail.fields

from django.db import migrations, models

import wagtail_link_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('link', wagtail_link_field.fields.LinkField(blank=True, null=True)),
                ('link_restricted', wagtail_link_field.fields.LinkField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestStreamFieldPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('link', 7), ('link_optional', 9), ('link_restricted', 11)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal-link', 'Internal page'), ('document-link', 'Document'), ('external-link', 'External URL'), ('anchor-link', 'Anchor'), ('email-link', 'Email'), ('phone-link', 'Phone'), ('custom-link', 'Custom URL')], 'label': 'Link type'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Append to the page URL: #anchor, ?query=value, or both (e.g., ?utm_source=newsletter#section)', 'label': 'URL suffix (optional)', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Element ID without the # symbol', 'label': 'Anchor', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for email, phone and custom links', 'label': 'URL / address', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('action', 0), ('internal_link', 1), ('page_query_string', 2), ('external_link', 3), ('document_link', 4), ('anchor_link', 5), ('url_link', 6)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', '---'), ('internal-link', 'Internal page'), ('document-link', 'Document'), ('external-link', 'External URL'), ('anchor-link', 'Anchor'), ('email-link', 'Email'), ('phone-link', 'Phone'), ('custom-link', 'Custom URL')], 'label': 'Link type', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('action', 8), ('internal_link', 1), ('page_query_string', 2), ('external_link', 3), ('document_link', 4), ('anchor_link', 5), ('url_link', 6)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal-link', 'Internal page'), ('document-link', 'Document')], 'label': 'Link type'}), 11: ('wagtail.blocks.StructBlock', [[('action', 10), ('internal_link', 1), ('page_query_string', 2), ('external_link', 3), ('document_link', 4), ('anchor_link', 5), ('url_link', 6)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
