[tox]
min_version = 4.11

envlist =
    python3.10-django4.2-wagtail6.3
    python3.11-django4.2-wagtail6.3
    python3.12-django4.2-wagtail6.3
    python3.12-django5.2-wagtail7.0
    python3.12-django5.2-wagtail7.2
    python3.13-django5.2-wagtail7.0
    python3.13-django5.2-wagtail7.2

[gh-actions]
python =
    3.10: python3.10
    3.11: python3.11
    3.12: python3.12
    3.13: python3.13

[testenv]
package = editable
pass_env =
    FORCE_COLOR
    NO_COLOR

use_frozen_constraints = true
constrain_package_deps = true

extras = testing

deps =
    django4.2: Django>=4.2,<5.0
    django5.2: Django>=5.2,<5.3

    wagtail6.3: wagtail>=6.3,<6.4
    wagtail7.0: wagtail>=7.0,<7.1
    wagtail7.2: wagtail>=7.2,<7.3

install_command = python -Im pip install --upgrade {opts} {packages}
commands =
    python -Im coverage run testmanage.py test {posargs: -v 2}

[testenv:coverage-report]
base_python = python3.13
package = skip
deps =
    coverage>=7.0,<8.0
commands =
    python -Im coverage combine
    python -Im coverage report -m

[testenv:interactive]
description = An interactive environment for local testing purposes
basepython = python3.13
deps =
    wagtail>=7.0,<7.3
    Django>=5.2,<5.3

commands_pre =
    python {toxinidir}/testmanage.py makemigrations
    python {toxinidir}/testmanage.py migrate
    python {toxinidir}/testmanage.py shell -c "from django.contrib.auth.models import User;(not User.objects.filter(username='admin').exists()) and User.objects.create_superuser('admin', 'super@example.com', 'changeme')"
    python {toxinidir}/testmanage.py createcachetable

commands =
    {posargs:python testmanage.py runserver 0.0.0.0:8020}

setenv =
    INTERACTIVE = 1
